export const product = [
  {
    id: 13,
    description: "Burger",
    text: "Delicious burger with all the fixings.",
    price: 8.99,
    img: "burger.png",
  },
  {
    id: 14,
    description: "Pizza",
    text: "A classic pizza with your choice of toppings.",
    price: 12.99,
    img: "pizza.png",
  },
  {
    id: 15,
    description: "Spaghetti",
    text: "Homemade spaghetti with marinara sauce.",
    price: 9.99,
    img: "Spaghetti.avif",
  },
  {
    id: 16,
    description: "Salad",
    text: "Fresh garden salad with dressing.",
    price: 5.99,
    img: "Salad.avif",
  },
  {
    id: 17,
    description: "Sushi",
    text: "Assorted sushi rolls and sashimi.",
    price: 15.99,
    img: "Sushi.avif",
  },
  {
    id: 18,
    description: "Tacos",
    text: "Tasty tacos with your choice of fillings.",
    price: 7.99,
    img: "tacos.avif",
  },
  {
    id: 19,
    description: "Chicken Wings",
    text: "Spicy and crispy chicken wings.",
    price: 10.99,
    img: "Chicken Wings.avif",
  },
  {
    id: 20,
    description: "Steak",
    text: "Juicy steak cooked to perfection.",
    price: 18.99,
    img: "Steak.avif",
  },
  {
    id: 21,
    description: "Fish and Chips",
    text: "Classic fish and chips with tartar sauce.",
    price: 11.99,
    img: "Fish and Chips.avif",
  },
  {
    id: 22,
    description: "Pasta Alfredo",
    text: "Creamy pasta Alfredo with garlic bread.",
    price: 12.99,
    img: "Pasta Alfredo.jpg",
  },
  {
    id: 23,
    description: "Caesar Salad",
    text: "Caesar salad with croutons and parmesan.",
    price: 6.99,
    img: "Caesar Salad.avif",
  },
  {
    id: 24,
    description: "Fried Rice",
    text: "Asian-style fried rice with vegetables and soy sauce.",
    price: 9.99,
    img: "Fried Rice.avif",
  },
  {
    id: 25,
    description: "Margarita",
    text: "Refreshing margarita cocktail with lime.",
    price: 7.99,
    img: "Margarita.avif",
  },
  {
    id: 26,
    description: "Ice Cream",
    text: "Assorted flavors of creamy ice cream.",
    price: 4.99,
    img: "Ice Cream.avif",
  },
  {
    id: 27,
    description: "Grilled Cheese Sandwich",
    text: "Classic grilled cheese with tomato soup.",
    price: 6.99,
    img: "Grilled Cheese Sandwich.avif",
  },
  {
    description: 28,
    description: "Pho",
    text: "Vietnamese noodle soup with herbs and meat.",
    price: 10.99,
    img: "pho.avif",
  },
  {
    id: 29,
    description: "Quesadilla",
    text: "Cheesy quesadilla with salsa and guacamole.",
    price: 8.99,
    img: "Quesadilla.avif",
  },
  {
    id: 30,
    description: "Pancakes",
    text: "Fluffy pancakes with syrup and butter.",
    price: 5.99,
    img: "Pancakes.avif",
  },
  {
    id: 31,
    description: "Burrito",
    text: "Hearty burrito with rice, beans, and choice of meat.",
    price: 9.99,
    img: "Burrito.avif",
  },
  {
    id: 32,
    description: "Fruit Salad",
    text: "Fresh fruit salad with a variety of fruits.",
    price: 7.99,
    img: "Fruit Salad.avif",
  },
  {
    id: 33,
    description: "Steamed Veg Momos",
    text: "Delicious steamed momos filled with a mix of vegetables.",
    img: "Steamed Veg Momos.avif",
    price: 5.99,
  },
  {
    id: 34,
    description: "Chicken Momos",
    text: "Mouthwatering momos stuffed with seasoned chicken.",
    img: "Chicken Momos.avif",
    price: 7.99,
  },
  {
    id: 35,
    description: "Paneer Momos",
    text: "Soft and flavorful momos with a paneer (Indian cottage cheese) filling.",
    img: "Panner Momos.avif",
    price: 6.49,
  },
  {
    id: 36,
    description: "Pork Momos",
    text: "Savory momos filled with seasoned pork and spices.",
    img: "Pork Momos.avif",
    price: 8.99,
  },
  {
    id: 37,
    description: "Fried Veg Momos",
    text: "Crispy fried momos with a delicious vegetable filling.",
    img: "Fried Veg Momos.jpg",
    price: 6.99,
  },
  {
    id: 38,
    description: "Mutton Momos",
    text: "Tender momos filled with succulent mutton and herbs.",
    img: "Mutton Momos.avif",
    price: 9.99,
  },
];
