
export const roomdetail = [
    {
      id: 1,
      description: "Deluxe Room",
      text: "A spacious and luxurious room with a king-size bed.",
      price: 1500,
      capacity: 2,
      amenities: ["Free Wi-Fi", "Minibar", "Flat-screen TV", "Balcony"],
      img: "business.avif",
      breakfast:"BreakFast Included",
      dinner:"Dinner Included",
      snakes:"Snakes Included",
      room:2
    },
    {
      id: 2,
      description: "Superior Suite",
      text: "An elegant suite with a separate living area and bedroom.",
      price: 2200,
      capacity: 2,
      amenities: ["Free Wi-Fi", "Minibar", "Spa access", "Sea view"],
      img: "Superior Suite.avif",
      breakfast:"BreakFast Included",
      dinner:"Dinner Included",
      snakes:"Snakes Excluded",
      room:4
    },
    {
      id: 3,
      description: "Standard Room",
      text: "A comfortable room with a queen-size bed and garden view.",
      price: 1000,
      capacity: 2,
      amenities: ["Free Wi-Fi", "Minibar", "Garden view", "Coffee maker"],
      img: "Standard Room.avif",
      breakfast:"BreakFast Excluded",
      dinner:"Dinner Included",
      snakes:"Snakes Excluded",
     
      room:2
    },
    {
      id: 4,
      description: "Luxury Suite",
      text: "A lavish suite with a private jacuzzi and oceanfront balcony.",
      price: 3000,
      capacity: 2,
      amenities: ["Free Wi-Fi", "Minibar", "Ocean view", "Jacuzzi"],
      img: "Luxury Suite.avif",breakfast:"BreakFast Included",
      dinner:"Dinner Included",
      snakes:"Snakes Included",
      room:5
    },
    {
      id: 5,
      description: "Family Suite",
      text: "A spacious suite with two bedrooms and a living room.",
      price: 2600,
      capacity: 4,
      amenities: ["Free Wi-Fi", "Minibar", "Mountain view", "Kitchenette"],
      img: "Family Suite.avif",
      breakfast:"BreakFast Included",
      dinner:"Dinner Included",
      snakes:"Snakes Included",
      room:2
    },
    {
      id: 6,
      description: "Executive Room",
      text: "An executive room with a private workspace and city view.",
      price: 1800,
      capacity: 2,
      amenities: ["Free Wi-Fi", "Minibar", "City view", "Work desk"],
      img: "Executive Room.avif",
      breakfast:"BreakFast Included",
      dinner:"Dinner Excluded",
      snakes:"Snakes Excluded",
      room:7
    },
    {
      id: 7,
      description: "Penthouse Suite",
      text: "A luxurious penthouse with a rooftop terrace and spa access.",
      price: 4500,
      capacity: 2,
      amenities: ["Free Wi-Fi", "Minibar", "Spa access", "Rooftop terrace"],
      img: "Penthouse Suite.avif",
      breakfast:"BreakFast Included",
      dinner:"Dinner Excluded",
      snakes:"Snakes Excluded",
      room:1
    },
    {
      id: 8,
      description: "Studio Apartment",
      text: "A studio apartment with a kitchenette and mountain view.",
      price: 1300,
      capacity: 2,
      amenities: ["Free Wi-Fi", "Kitchenette", "Mountain view", "Sofa bed"],
      img: "Studio Apartment.avif",
      breakfast:"BreakFast Excluded",
      dinner:"Dinner Included",
      snakes:"Snakes Included",
      room:2
    },
    {
      id: 9,
      description: "Ocean View Room",
      text: "A cozy room with a view of the ocean and a private balcony.",
      price: 1700,
      capacity: 2,
      amenities: ["Free Wi-Fi", "Minibar", "Ocean view", "Private balcony"],
      img: "Ocean View Room.avif",
      breakfast:"BreakFast Included",
      dinner:"Dinner Excluded",
      snakes:"Snakes Excluded",
      room:3
    },
    {
      id: 10,
      description: "Honeymoon Suite",
      text: "A romantic suite with a four-poster bed and champagne on arrival.",
      price: 280,
      capacity: 2,
      amenities: ["Free Wi-Fi", "Minibar", "Champagne", "Four-poster bed"],
      img: "honeymoon-suite.avif",
      breakfast:"BreakFast Included",
      dinner:"Dinner Included",
      snakes:"Snakes Included",
      room:5
    },
    {
      id: 11,
      description: "Business Room",
      text: "A room designed for business travelers with a work desk and free breakfast.",
      price: 1200,
      capacity: 1,
      amenities: ["Free Wi-Fi", "Work desk", "Free breakfast", "City view"],
      img: "bussiness.avif",
      breakfast:"BreakFast Included",
      dinner:"Dinner Included",
      snakes:"Snakes EXcluded",
      room:5
    },
    {
      id: 12,
      description: "Cottage",
      text: "A cozy cottage with a fireplace and forest view.",
      price: 2000,
      capacity: 2,
      amenities: ["Free Wi-Fi", "Fireplace", "Forest view", "Kitchenette"],
      img: "cottage.avif",
      breakfast:"BreakFast Included",
      dinner:"Dinner Included",
      
      snakes:"Snakes Excluded",
      room:10
    },
    {
      id: 13,
      description: "Beachfront Bungalow",
      text: "A beachfront bungalow with a private beach access and hammocks.",
      price: 3500,
      capacity: 2,
      amenities: ["Free Wi-Fi", "Private beach access", "Hammocks", "Ocean view"],
      img: "beachfront-bungalow.avif",
      breakfast:"BreakFast Included",
      dinner:"Dinner Ex0cluded",
      snakes:"Snakes Included",
      room:5
    },
    {
      id: 14,
      description: "Pet-Friendly Room",
      text: "A room suitable for travelers with pets, including a pet bed and bowls.",
      price: 1400,
      capacity: 2,
      amenities: ["Free Wi-Fi", "Pet-friendly", "City view", "Pet amenities"],
      img: "Pet-Friendly Room.avif",
      breakfast:"BreakFast Included",
      dinner:"Dinner Included",
      snakes:"Snakes Included",
      room:2
    },
    {
      id: 15,
      description: "Ski Chalet",
      text: "A ski chalet with ski-in/ski-out access and a hot tub.",
      price: 2400,
      capacity: 4,
      amenities: ["Free Wi-Fi", "Ski access", "Hot tub", "Mountain view"],
      img: "ski-chalet.avif",
      breakfast:"BreakFast Included",
      dinner:"Dinner Included",
      snakes:"Snakes Included",
      room:2
    },
  ];
  